### PR TITLE
detect retina

### PR DESCRIPTION
**Pull request by Haroenv**
bad side: will load high detail map and show it small, IMO same-detail would be better.

screen shot 2016-01-12 at 22 20 48

[reference](http://leafletjs.com/reference.html#tilelayer-detectretina)

### CODE REVIEW

**Comment by Haroenv** [comment]
Fixed that, now looks like 

screen shot 2016-01-12 at 22 49 45

Other tiles are probably possible too.

**Comment by mischah** [comment]
:ok_hand:

**Comment by Haroenv** [comment]
https://github.com/leaflet-extras/leaflet-providers a list of other maps, don't know which ones can be retina

**Comment by LukyVj** [comment]
Ready to merde ? Seems good to me :leaves: 
Except that I don't like the black color, I'm up for adding the bullgit blue color as @JohJakob suggsted :trophy:

**Comment by Haroenv** [comment]
In case the black isn't good, afaik we could also take the watercolour tiles http://maps.stamen.com/watercolor/#12/37.7706/-122.3781

**Comment by LukyVj** [comment]
Can't we just decrase the opacity
 ?

**Comment by Haroenv** [comment]
I think a colour should be picked 😄, be it this one (stamen toner) or another one from the list i posted

**Pull request merged**
